name: meetingminutes-gpt
dependencies:
- python
- pip
- pip:
    - google-auth
    - google-auth-oauthlib
    - google-auth-httplib2
    - google-api-python-client
    - openai
    - transformers
    - dotenv

    #pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
